version: '3.8'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Passw0rd!1"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  flyway:
    image: flyway/flyway
    command: migrate
    depends_on:
      - mssql
    volumes:
      - ./flyway/conf:/flyway/conf
      - ./flyway/sql:/flyway/sql

volumes:
  mssql_data:
