name: "Database CI/CD"

on:
  push:
    branches: [ "main"]
    paths:
      - 'Database/flyway/migrations**'
  workflow_dispatch:

jobs:
  Migrate:
    name: RunMigration
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.0

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install awscli --upgrade --user
          echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc
          source ~/.bashrc

      - name: Retrieve secrets from AWS Secrets Manager
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}
          aws configure set region eu-west-1
          username=$(aws secretsmanager get-secret-value --secret-id mssql-server --query 'SecretString.username' --output text)
          password=$(aws secretsmanager get-secret-value --secret-id mssql-server --query 'SecretString.password' --output text)
          url=$(aws secretsmanager get-secret-value --secret-id mssql-server --query 'SecretString.url' --output text)

      - name: Create SpiderCards Database if not exists
        run: |
          sqlcmd -S $url -U $username -P $password -Q "IF DB_ID('spidercards') IS NULL BEGIN CREATE DATABASE SpiderCards; END GO"

      - name: Download and setup Flyway
        run: |
          wget -qO- https://download.red-gate.com/maven/release/com/redgate/flyway/flyway-commandline/10.7.1/flyway-commandline-10.7.1-linux-x64.tar.gz | tar -xvz && sudo ln -s `pwd`/flyway-10.7.1/flyway /usr/local/bin

      - name: Run Flyway migration
        run: |
          flyway -user="$username" -password="$password" -url="$url" -locations="filesystem:/flyway/migrations" migrate
